"""Assemble the GitHub Pages site. Run: uv run python build_site.py

The four reports are build artefacts, regenerated by their own scripts and
git-ignored in `out/`. This copies them into `docs/` — which is what Pages
serves — and writes an index that describes each one and says which figures
supersede which, because three of the four contain answers that a later phase
revised.

Deliberately dumb: it copies rather than regenerates. Run the analysis
scripts first; this only publishes what they produced, so the site can never
disagree with `out/`.
"""

from __future__ import annotations

import shutil
from datetime import date
from pathlib import Path

from pvnight.report import STYLE

# One entry per report, in the order a reader should meet them. `status`
# carries the supersession, which matters: two of these four pages reach
# conclusions that a later phase corrected, and a reader arriving from a
# search engine has no other way to know that.
REPORTS = [
    {
        "file": "report.html",
        "title": "The solar window",
        "phase": "Phase 1",
        "status": "current",
        "blurb": (
            "When solar generation is actually possible, derived from six "
            "years of five-minute history rather than from an almanac. "
            "Panels wake about three minutes before geometric sunrise, so "
            "the boundary is fitted to when they really start and stop, and "
            "the fit is what makes every later page's definition of "
            "&ldquo;night&rdquo; empirical."),
    },
    {
        "file": "night_report.html",
        "title": "Night consumption and battery sizing",
        "phase": "Phase 2",
        "status": "superseded",
        "blurb": (
            "The first attempt at sizing a battery, from PVOutput's own "
            "consumption channel. Kept because the method is sound and the "
            "comparison is instructive — but that channel was later found to "
            "have lost about a quarter of the household load from December "
            "2022, so its figures understate the night and the battery. Read "
            "the meter page instead."),
    },
    {
        "file": "meter_report.html",
        "title": "Night consumption, measured at the meter",
        "phase": "Phase 3 &amp; 4",
        "status": "current",
        "blurb": (
            "The same question rebuilt on smart-meter data, which measures "
            "what actually crosses the grid connection, then priced against "
            "a real 2027 tariff. Contains the fault that invalidated phase "
            "2, the winter wall that bounds any battery answer, and the "
            "capacity the euros actually justify."),
    },
    {
        "file": "battery_investment.html",
        "title": "Is the battery worth buying?",
        "phase": "Phase 4b",
        "status": "current",
        "blurb": (
            "A different question from all of the above: not what size, but "
            "whether to buy at all, for hardware already chosen, against "
            "leaving the money invested elsewhere. The manufacturer states "
            "two lifetimes and they disagree about the answer, which is the "
            "honest headline."),
    },
]

INDEX_CSS = """
.cards { display: grid; gap: 18px; margin: 28px 0 0; }
a.card {
  display: block; text-decoration: none; color: inherit;
  border: 1px solid var(--line); border-radius: 10px;
  background: var(--surface); padding: 20px 22px;
  transition: border-color .15s ease, transform .15s ease;
}
a.card:hover { border-color: var(--accent); transform: translateY(-1px); }
a.card h2 { margin: 6px 0 8px; font-size: 20px; }
a.card p { margin: 0; color: var(--muted); font-size: 15px; }
.tag {
  display: inline-block; font: 500 10px/1 "IBM Plex Mono", ui-monospace,
  monospace; letter-spacing: .08em; text-transform: uppercase;
  padding: 4px 7px; border-radius: 4px; margin-left: 8px;
  border: 1px solid var(--line); color: var(--muted); vertical-align: 2px;
}
.tag.superseded { color: #d95926; border-color: #d9592655; }
footer { margin-top: 44px; color: var(--muted); font-size: 14px; }
"""


def build_index(reports: list[dict], generated: str) -> str:
    cards = "".join(
        f'<a class="card" href="{r["file"]}">'
        f'<p class="eyebrow">{r["phase"]}'
        + ('<span class="tag superseded">superseded</span>'
           if r["status"] == "superseded" else "")
        + f'</p><h2>{r["title"]}</h2><p>{r["blurb"]}</p></a>'
        for r in reports)
    return (
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        "<title>Solar, night consumption and a battery</title>"
        + STYLE
        + f"<style>{INDEX_CSS}</style></head><body><main>"
        '<p class="eyebrow">A home PV installation, measured</p>'
        "<h1>Solar, night consumption, and whether a battery pays</h1>"
        '<p class="lede">Four reports, built from six years of five-minute '
        "solar history and fifteen-minute smart-meter data. They were "
        "written in order, and each one changed the answer the previous had "
        "reached — including one that found a hardware fault which "
        "invalidated an entire phase. Every figure on these pages is "
        "computed from the data beside it.</p>"
        f'<div class="cards">{cards}</div>'
        "<footer>Generated "
        f"{generated} from <a href=\"https://github.com/jvhaarst/pvhistory\">"
        "github.com/jvhaarst/pvhistory</a>. The underlying measurements are "
        "not published; the derived tables in <code>out/</code> are."
        "</footer></main></body></html>")


def run(repo_root: Path) -> dict:
    repo_root = Path(repo_root)
    out, docs = repo_root / "out", repo_root / "docs"
    docs.mkdir(parents=True, exist_ok=True)

    missing = [r["file"] for r in REPORTS if not (out / r["file"]).exists()]
    if missing:
        raise FileNotFoundError(
            f"missing reports: {missing}. Run analyze.py, analyze_night.py, "
            "analyze_meter.py and analyze_investment.py first — this script "
            "publishes what they produced and never regenerates it.")

    for r in REPORTS:
        shutil.copy2(out / r["file"], docs / r["file"])

    generated = date.today().isoformat()
    (docs / "index.html").write_text(build_index(REPORTS, generated))
    return {"pages": len(REPORTS) + 1, "generated": generated,
            "dir": str(docs)}


if __name__ == "__main__":
    for k, v in run(Path(__file__).parent).items():
        print(f"{k}: {v}")
